### ISSUE TITLE
Ability to set tasks for any date in future. 

### ISSUE THREAD

**Issue by s9k96** [onejgordon/flow-dashboard#116] opened 2018-07-28 06:47 UTC
Now we can only setup tasks for tomorrow, it would be really good if we can set tasks for any date or at least the current week.

**Comment by onejgordon** [comment] 2018-11-13 03:01
Dupe of #30, though still concerned about the reproduction of calendar-like functionality. Integration with Google's (and others') tasks/reminders/calendar API may be more appropriate.

**Closed by onejgordon** 2018-11-13 03:01 UTC
