### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by junaid2314** [onejgordon/flow-dashboard#136] opened 2020-11-26 07:08 UTC
Does flow dash have any official image on docker hub? if no can we have that on docker. thanks

**Comment by projx** [comment] 2021-01-10 19:00
I'd especially love to see this..

**Comment by onejgordon** [comment] 2021-01-30 18:59
This is a duplicate of #42, so closing this one. I'd still love to offer a docker image, but am not aware of the support for GAE applications. If anyone has experience, would love to support this one.

**Closed as completed by onejgordon** 2021-01-30 18:59 UTC
